image:
  file: .gitpod.Dockerfile

ports:
  # Explorer port
  - port: 3000
  - port: 3999

tasks:
  - init: yarn
    command: yarn test:watch
  - command: explorer_start.sh
  - command: ./home/gitpod/clarity-repl
  - command: sidecar_start.sh

vscode:
  extensions:
    - blockstack.clarity@0.0.5:rBhb1NsIYs1/wpFyiyXNdA==
    - lgalabru.clarity-lsp@0.2.66:PEBgheot/B02RfVLfwbzYg==
    - hbenl.vscode-test-explorer@2.19.1:GtY0wSp3pjUeyKXi8mFMnQ==
    - hbenl.vscode-mocha-test-adapter@2.5.0:tO3QPW+E2y09egEKoMFAhg==
    - 2gua.rainbow-brackets@0.0.6:Tbu8dTz0i+/bgcKQTQ5b8g==
    - Durzn.brackethighlighter@1.8.1:qgOEXJ2k9WNEZJ3sbYgKjw==